---
title: "P8105_HW1_BJL2150"
author: "Briana Lettsome"
date: "September 21, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


# Problem 1


## Creating data frame

```{r}
Problem1_df = tibble(
  x = runif(10, min=0, max=5), 
  vec_numeric = c(x>2),
  vec_char = c("Giraffe", "Elephant", "Lion", "Wolf", "Dolphin", "Ant", "Dog", 
               "Tiger", "Bird", "Fish" ),
  vec_logical = c(TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 
                  FALSE),
  vec_factor = factor(c("African descent", "White", "Asian", "Native American", 
                        "Virgin Islander", "St. Thomian", "St. Johnian", "Crucian", 
                        "Floridian", "Atlantian"))
  )
```
 
```{r} 
# Taking mean of x variable

mean(Problem1_df$x)

# This works because it is numeric variable. 
#The mean of x equals 2.136482.
```

```{r}
# Taking mean of vec_numeric

mean(Problem1_df$vec_numeric)

# Taking the mean of this equals 0.3. 
#Therefore, this works.
```

```{r}
# Taking mean of vec_char

mean(Problem1_df$vec_char)

# This code does not work. 
#Error message says that "this argument is not numeric or logical".
```

```{r}
# Taking mean of vec_logical

mean(Problem1_df$vec_logical)

# This code does output a value for the mean of the logical vector.
# The mean of this vector equals 0.4.
```

```{r}
# Taking the mean of vec_factor

mean(Problem1_df$vec_factor)

#This code does not work becasue th vector is not numeric or logical.
```

```{r}
## 1st code chunk
# Using the as.numeric function to the logical, character and factor vectors.

as.numeric(Problem1_df$vec_logical)

as.numeric(Problem1_df$vec_char)

as.numeric(Problem1_df$vec_factor)

# When this function was used on the logical and factor vectors, numeric values
# were created.
# With the character vector, it could not be applied (NA).

```

```{r}
# 2nd code chunk
# Converting character variable from character to factor to numeric

## Created a new variable named 'Factor' that is the end product of converting
# the character vector to the factor vector.

Factor = as.factor(Problem1_df$vec_char)

#Converted the Factor variable to a numeric vector.

as.numeric(Factor)


## Converting factor variable from factor to character to numeric

Character = as.character(Problem1_df$vec_factor)

as.numeric(Character)

# In the first portion of the code chunk, the character vector was converted
# from a character to a factor and lastly to a numeric vector. This vector was
# converted successfully into the factor the numeric vectors. 

# Conversion of the factor vector to the character vector was successsful. 
# However, converting that new vector *Character) into a numeric vector was
# not successful. An error message showed.
```

## Problem 2
```{r}
# Created data frame for Problem 2
x = rnorm(1000)
y = rnorm(1000)
vec_logical = c(x + y > 0)

Problem2_df = tibble(
  x,
  y,
  vec_logical)

vec_numeric = as.numeric(Problem2_df$vec_logical)
vec_factor = as.factor(Problem2_df$vec_logical)

mean(x)
median(x)
dim(x)
```
The mean of the x is `r mean(x)`.

The median of the x is `r median(x)`.

The dataset size is dim


## Scatterplots
```{r}
# Making scatter plots for logical, numeric and factor vectors, respectively.

ggplot(Problem2_df, aes(x = y, y = x)) + geom_point(aes(color = vec_logical))

ggplot(Problem2_df, aes(x = y, y = x)) + geom_point(aes(color = vec_numeric))

ggplot(Problem2_df, aes(x = y, y = x)) + geom_point(aes(color = vec_factor))
```