P8105\_HW1\_BJL2150
================
Briana Lettsome
September 21, 2018

Problem 1
=========

Creating data frame
-------------------

``` r
Problem1_df = tibble(
  x = runif(10, min=0, max=5), 
  vec_numeric = c(x>2),
  vec_char = c("Giraffe", "Elephant", "Lion", "Wolf", "Dolphin", "Ant", "Dog", 
               "Tiger", "Bird", "Fish" ),
  vec_logical = c(TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 
                  FALSE),
  vec_factor = factor(c("African descent", "White", "Asian", "Native American", 
                        "Virgin Islander", "St. Thomian", "St. Johnian", "Crucian", 
                        "Floridian", "Atlantian"))
  )
```

``` r
# Taking mean of x variable

mean(Problem1_df$x)
```

    ## [1] 3.219754

``` r
# This works because it is numeric variable. The mean of x equals 2.136482.
```

``` r
# Taking mean of vec_numeric

mean(Problem1_df$vec_numeric)
```

    ## [1] 0.8

``` r
# Taking the mean of this equals 0.3. 
#Therefore, this works.
```

``` r
# Taking mean of vec_char

mean(Problem1_df$vec_char)
```

    ## Warning in mean.default(Problem1_df$vec_char): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
# This code does not work. Error message says that "this argument is not numeric or logical".
```

``` r
# Taking mean of vec_logical

mean(Problem1_df$vec_logical)
```

    ## [1] 0.4

``` r
# This code does output a value for the mean of the logical vector.
# The mean of this vector equals 0.4.
```

``` r
# Taking the mean of vec_factor

mean(Problem1_df$vec_factor)
```

    ## Warning in mean.default(Problem1_df$vec_factor): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
#This code does not work becasue th vector is not numeric or logical.
```

``` r
## 1st code chunk
# Using the as.numeric function to the logical, character and factor vectors.

as.numeric(Problem1_df$vec_logical)
```

    ##  [1] 1 1 0 0 0 1 0 0 1 0

``` r
as.numeric(Problem1_df$vec_char)
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(Problem1_df$vec_factor)
```

    ##  [1]  1 10  2  6  9  8  7  4  5  3

``` r
# When this function was used on the logical and factor vectors, numeric values
# were created.
# With the character vector, it could not be applied (NA).
```

``` r
# 2nd code chunk
# Converting character variable from character to factor to numeric

## Created a new variable named 'Factor' that is the end product of converting
# the character vector to the factor vector.

Factor = as.factor(Problem1_df$vec_char)

#Converted the Factor variable to a numeric vector.

as.numeric(Factor)
```

    ##  [1]  7  5  8 10  4  1  3  9  2  6

``` r
## Converting factor variable from factor to character to numeric

Character = as.character(Problem1_df$vec_factor)

as.numeric(Character)
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
# In the first portion of the code chunk, the character vector was converted
# from a character to a factor and lastly to a numeric vector. This vector was
# converted successfully into the factor the numeric vectors. 

# Conversion of the factor vector to the character vector was successsful. 
# However, converting that new vector *Character) into a numeric vector was
# not successful. An error message showed.
```

Problem 2
---------

``` r
# Created data frame for Problem 2
x = rnorm(1000)
y = rnorm(1000)
vec_logical = c(x + y > 0)

Problem2_df = tibble(
  x,
  y,
  vec_logical)

vec_numeric = as.numeric(Problem2_df$vec_logical)
vec_factor = as.factor(Problem2_df$vec_logical)

mean(x)
```

    ## [1] -0.04009163

``` r
median(x)
```

    ## [1] -0.004100366

``` r
dim(x)
```

    ## NULL

The mean of the x is -0.0400916.

The median of the x is -0.0041004.

The dataset size is dim

Scatterplots
------------

``` r
# Making scatter plots for logical, numeric and factor vectors, respectively.

Logical = ggplot(Problem2_df, aes(x = y, y = x)) + geom_point(aes(color = vec_logical))

# The blue data points on the scatterplot represent the values which are TRUE.
# The pink data points represent those values that are FALSE.


Numeric = ggplot(Problem2_df, aes(x = y, y = x)) + geom_point(aes(color = vec_numeric))

# The blue data points represent values numeric values equal to 1.00.
# The black data points represent numeric values that are equal to 0.00. 

Factor = ggplot(Problem2_df, aes(x = y, y = x)) + geom_point(aes(color = vec_factor))

# The blue data points represent factor variables that are TRUE.
# The blue data points relect factor variables that are FALSE.
```
